DROP TABLE IF EXISTS student, staff, staff_study, study, student_choice, supervisor, moderator;

CREATE TABLE supervisor (
    supervisorID SERIAL PRIMARY KEY,
    supervisorFName varchar(100),
    supervisorLName varchar(100),
    supervisorSlots int DEFAULT 0,
    course varchar(100)
);

CREATE TABLE moderator (
    moderatorID SERIAL PRIMARY KEY,
    moderatorFName varchar(100),
    moderatorLName varchar(100),
    moderatorSlots int DEFAULT 0,
    course varchar(100)
);

CREATE TABLE student (
    studentID  SERIAL PRIMARY KEY,
    firstName varchar(100),
    lastName varchar(100),
    course varchar(100),
    supervisorID INT REFERENCES supervisor(supervisorID) DEFAULT 1,
    moderatorID INT REFERENCES moderator(moderatorID) DEFAULT 1,
    markSup BOOLEAN
);

CREATE TABLE student_choice (
    studentID INT REFERENCES student(studentID),
    choice1 INT REFERENCES supervisor(supervisorID) DEFAULT 1,
    choice2 INT REFERENCES supervisor(supervisorID) DEFAULT 1,
    choice3 INT REFERENCES supervisor(supervisorID) DEFAULT 1
);

-- dummy data to test generated by mockaroo
-- INSERT INTO supervisor (supervisorFName, supervisorLName) VALUES ('Place', 'Holder');
-- INSERT INTO supervisor (supervisorFName, supervisorLName) VALUES ('Lincoln', 'Seddon');
-- INSERT INTO supervisor (supervisorFName, supervisorLName) VALUES ('Daryl', 'Hakking');
-- INSERT INTO supervisor (supervisorFName, supervisorLName) VALUES ('Kathi', 'Angeau');
-- INSERT INTO supervisor (supervisorFName, supervisorLName) VALUES ('Anatol', 'Costard');
-- INSERT INTO supervisor (supervisorFName, supervisorLName) VALUES ('Luz', 'Philpots');
-- INSERT INTO supervisor (supervisorFName, supervisorLName) VALUES ('Korney', 'Undrell');
-- INSERT INTO supervisor (supervisorFName, supervisorLName) VALUES ('Ruthie', 'Sheather');
-- INSERT INTO supervisor (supervisorFName, supervisorLName) VALUES ('Emmi', 'Kemer');
-- INSERT INTO supervisor (supervisorFName, supervisorLName) VALUES ('Ev', 'Mellon');
-- INSERT INTO supervisor (supervisorFName, supervisorLName) VALUES ('Bondie', 'Crick');
-- INSERT INTO supervisor (supervisorFName, supervisorLName) VALUES ('Elie', 'Swatradge');
-- INSERT INTO supervisor (supervisorFName, supervisorLName) VALUES ('Talbert', 'Gradley');
-- INSERT INTO supervisor (supervisorFName, supervisorLName) VALUES ('Standford', 'Moncreiff');
-- INSERT INTO supervisor (supervisorFName, supervisorLName) VALUES ('Miof mela', 'MacAskie');
-- INSERT INTO supervisor (supervisorFName, supervisorLName) VALUES ('Ellynn', 'Lawley');
-- INSERT INTO supervisor (supervisorFName, supervisorLName) VALUES ('Bren', 'Boniface');
-- INSERT INTO supervisor (supervisorFName, supervisorLName) VALUES ('Gianina', 'Earle');
-- INSERT INTO supervisor (supervisorFName, supervisorLName) VALUES ('Codee', 'Droghan');
-- INSERT INTO supervisor (supervisorFName, supervisorLName) VALUES ('Alexandra', 'Lilleycrop');
-- INSERT INTO supervisor (supervisorFName, supervisorLName) VALUES ('Ferrel', 'O''Doherty');
-- INSERT INTO supervisor (supervisorFName, supervisorLName) VALUES ('Danielle', 'Cozens');
-- INSERT INTO supervisor (supervisorFName, supervisorLName) VALUES ('Amata', 'Wagg');
-- INSERT INTO supervisor (supervisorFName, supervisorLName) VALUES ('Sherm', 'Rourke');
-- INSERT INTO supervisor (supervisorFName, supervisorLName) VALUES ('Pernell', 'McCandless');
-- INSERT INTO supervisor (supervisorFName, supervisorLName) VALUES ('Ivette', 'Mines');
-- INSERT INTO supervisor (supervisorFName, supervisorLName) VALUES ('Yolanthe', 'Oyley');
-- INSERT INTO supervisor (supervisorFName, supervisorLName) VALUES ('Seymour', 'Kearsley');
-- INSERT INTO supervisor (supervisorFName, supervisorLName) VALUES ('Jefferey', 'Zecchi');
-- INSERT INTO supervisor (supervisorFName, supervisorLName) VALUES ('Brocky', 'Poundesford');
-- INSERT INTO supervisor (supervisorFName, supervisorLName) VALUES ('Marquita', 'Lomath');

-- INSERT INTO moderator (moderatorFName, moderatorLName) VALUES ('Place', 'Holder');
-- INSERT INTO moderator (moderatorFName, moderatorLName) VALUES ('Lincoln', 'Seddon');
-- INSERT INTO moderator (moderatorFName, moderatorLName) VALUES ('Daryl', 'Hakking');
-- INSERT INTO moderator (moderatorFName, moderatorLName) VALUES ('Kathi', 'Angeau');
-- INSERT INTO moderator (moderatorFName, moderatorLName) VALUES ('Anatol', 'Costard');
-- INSERT INTO moderator (moderatorFName, moderatorLName) VALUES ('Luz', 'Philpots');
-- INSERT INTO moderator (moderatorFName, moderatorLName) VALUES ('Korney', 'Undrell');
-- INSERT INTO moderator (moderatorFName, moderatorLName) VALUES ('Ruthie', 'Sheather');
-- INSERT INTO moderator (moderatorFName, moderatorLName) VALUES ('Emmi', 'Kemer');
-- INSERT INTO moderator (moderatorFName, moderatorLName) VALUES ('Ev', 'Mellon');
-- INSERT INTO moderator (moderatorFName, moderatorLName) VALUES ('Bondie', 'Crick');
-- INSERT INTO moderator (moderatorFName, moderatorLName) VALUES ('Elie', 'Swatradge');
-- INSERT INTO moderator (moderatorFName, moderatorLName) VALUES ('Talbert', 'Gradley');
-- INSERT INTO moderator (moderatorFName, moderatorLName) VALUES ('Standford', 'Moncreiff');
-- INSERT INTO moderator (moderatorFName, moderatorLName) VALUES ('Miof mela', 'MacAskie');
-- INSERT INTO moderator (moderatorFName, moderatorLName) VALUES ('Ellynn', 'Lawley');
-- INSERT INTO moderator (moderatorFName, moderatorLName) VALUES ('Bren', 'Boniface');
-- INSERT INTO moderator (moderatorFName, moderatorLName) VALUES ('Gianina', 'Earle');
-- INSERT INTO moderator (moderatorFName, moderatorLName) VALUES ('Codee', 'Droghan');
-- INSERT INTO moderator (moderatorFName, moderatorLName) VALUES ('Alexandra', 'Lilleycrop');
-- INSERT INTO moderator (moderatorFName, moderatorLName) VALUES ('Ferrel', 'O''Doherty');
-- INSERT INTO moderator (moderatorFName, moderatorLName) VALUES ('Danielle', 'Cozens');
-- INSERT INTO moderator (moderatorFName, moderatorLName) VALUES ('Amata', 'Wagg');
-- INSERT INTO moderator (moderatorFName, moderatorLName) VALUES ('Sherm', 'Rourke');
-- INSERT INTO moderator (moderatorFName, moderatorLName) VALUES ('Pernell', 'McCandless');
-- INSERT INTO moderator (moderatorFName, moderatorLName) VALUES ('Ivette', 'Mines');
-- INSERT INTO moderator (moderatorFName, moderatorLName) VALUES ('Yolanthe', 'Oyley');
-- INSERT INTO moderator (moderatorFName, moderatorLName) VALUES ('Seymour', 'Kearsley');
-- INSERT INTO moderator (moderatorFName, moderatorLName) VALUES ('Jefferey', 'Zecchi');
-- INSERT INTO moderator (moderatorFName, moderatorLName) VALUES ('Brocky', 'Poundesford');
-- INSERT INTO moderator (moderatorFName, moderatorLName) VALUES ('Marquita', 'Lomath');

