CREATE ROLE Seth superuser;

DROP TABLE IF EXISTS student, staff, staff_study, study, student_choice;

CREATE TABLE staff (
    staffID SERIAL PRIMARY KEY,
    firstName varchar(100),
    lastName varchar(100),
    supervisorSlots int DEFAULT 0,
    moderatorSlots int DEFAULT 0
);

CREATE TABLE study (
    areaID SERIAL PRIMARY KEY,
    areaName VARCHAR(256)
);

CREATE TABLE student (
    studentID  VARCHAR(10) PRIMARY KEY,
    firstName varchar(100),
    lastName varchar(100),
    supervisorID INT REFERENCES staff(staffID) DEFAULT 1,
    moderatorID INT REFERENCES staff(staffID) DEFAULT 1,
    course varchar(100)
);

CREATE TABLE student_choice (
    studentID VARCHAR(10) REFERENCES student(studentID),
    choice1 INT REFERENCES staff(staffID),
    choice2 INT REFERENCES staff(staffID),
    choice3 INT REFERENCES staff(staffID)
);

CREATE TABLE staff_study (
    areaID INT REFERENCES study(areaID),
    staffID INT REFERENCES staff(staffID)
);

-- dummy data to test generated by mockaroo
INSERT INTO staff (firstName, lastName) VALUES ('Place', 'Holder');
INSERT INTO staff (firstName, lastName) VALUES ('Lincoln', 'Seddon');
INSERT INTO staff (firstName, lastName) VALUES ('Daryl', 'Hakking');
INSERT INTO staff (firstName, lastName) VALUES ('Kathi', 'Angeau');
INSERT INTO staff (firstName, lastName) VALUES ('Anatol', 'Costard');
INSERT INTO staff (firstName, lastName) VALUES ('Luz', 'Philpots');
INSERT INTO staff (firstName, lastName) VALUES ('Korney', 'Undrell');
INSERT INTO staff (firstName, lastName) VALUES ('Ruthie', 'Sheather');
INSERT INTO staff (firstName, lastName) VALUES ('Emmi', 'Kemer');
INSERT INTO staff (firstName, lastName) VALUES ('Ev', 'Mellon');
INSERT INTO staff (firstName, lastName) VALUES ('Bondie', 'Crick');
INSERT INTO staff (firstName, lastName) VALUES ('Elie', 'Swatradge');
INSERT INTO staff (firstName, lastName) VALUES ('Talbert', 'Gradley');
INSERT INTO staff (firstName, lastName) VALUES ('Standford', 'Moncreiff');
INSERT INTO staff (firstName, lastName) VALUES ('Miof mela', 'MacAskie');
INSERT INTO staff (firstName, lastName) VALUES ('Ellynn', 'Lawley');
INSERT INTO staff (firstName, lastName) VALUES ('Bren', 'Boniface');
INSERT INTO staff (firstName, lastName) VALUES ('Gianina', 'Earle');
INSERT INTO staff (firstName, lastName) VALUES ('Codee', 'Droghan');
INSERT INTO staff (firstName, lastName) VALUES ('Alexandra', 'Lilleycrop');
INSERT INTO staff (firstName, lastName) VALUES ('Ferrel', 'O''Doherty');
INSERT INTO staff (firstName, lastName) VALUES ('Danielle', 'Cozens');
INSERT INTO staff (firstName, lastName) VALUES ('Amata', 'Wagg');
INSERT INTO staff (firstName, lastName) VALUES ('Sherm', 'Rourke');
INSERT INTO staff (firstName, lastName) VALUES ('Pernell', 'McCandless');
INSERT INTO staff (firstName, lastName) VALUES ('Ivette', 'Mines');
INSERT INTO staff (firstName, lastName) VALUES ('Yolanthe', 'Oyley');
INSERT INTO staff (firstName, lastName) VALUES ('Seymour', 'Kearsley');
INSERT INTO staff (firstName, lastName) VALUES ('Jefferey', 'Zecchi');
INSERT INTO staff (firstName, lastName) VALUES ('Brocky', 'Poundesford');
INSERT INTO staff (firstName, lastName) VALUES ('Marquita', 'Lomath');